language: elixir
# Test policy, where possible:
#  - should run on 3 latest minor Elixir releases.
#  - should run on 2 latest major OTP releases.
elixir:
  - 1.6.4
  - 1.5.3
otp_release:
  - 19.3
  - 20.3

sudo: false # To use faster container based build environment
script:
  - mix compile --warnings-as-errors
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - pmargreff@gmail.com
